# Uncomment the next line to define a global platform for your project
 platform :osx, '11.0'

target 'MacOSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Masonry'

end
