//
//  SunmiUSBPrinterManager.h
//  MacOSApp
//
//  Minimal USB transport for SUNMI USB printer-class devices.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

extern NSString * const SunmiUSBPrinterErrorDomain;

@interface SunmiUSBPrinterManager : NSObject

@property (nonatomic, readonly, getter=isConnected) BOOL connected;
@property (nonatomic, copy, readonly, nullable) NSString *deviceName;
@property (nonatomic, copy, readonly, nullable) NSString *serialNumber;
@property (nonatomic, assign, readonly) NSInteger vendorID;
@property (nonatomic, assign, readonly) NSInteger productID;

+ (instancetype)sharedManager;

/// Probes for the first SUNMI USB printer-class interface and records its identity.
- (BOOL)findPrinter:(NSError * _Nullable * _Nullable)error;

/// Sends raw printer command bytes to the USB bulk OUT endpoint.
/// The command bytes can be generated by SunmiPrinterCommand.
- (void)sendPrintData:(NSData *)data completion:(void(^)(NSError * _Nullable error))completion;

@end

NS_ASSUME_NONNULL_END
